spring.application.name=sqlite
spring.datasource.url=jdbc:sqlite:example.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
bug-fact.image-template=file:Cool-Bug-Facts-Meme.jpg
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
info.app.name=Cool Bug Fact API
info.app.description=API for managing and rendering bug facts
info.app.version=@project.version@